# Generated by Django 2.1.7 on 2019-07-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190710_0859'),
        ('users', '0002_auto_20190704_1433'),
    ]

    operations = [
    ]
