# Generated by Django 2.1.7 on 2019-05-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190525_1841'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
