# Generated by Django 2.1.7 on 2019-07-09 18:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190607_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.project_directory_path),
        ),
    ]
