# Generated by Django 2.1.7 on 2019-05-27 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20190526_0639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignees',
            new_name='Assignees',
        ),
        migrations.RemoveField(
            model_name='project',
            name='asignees',
        ),
        migrations.RemoveField(
            model_name='task',
            name='asigned_users',
        ),
        migrations.AddField(
            model_name='project',
            name='assignees',
            field=models.ManyToManyField(related_name='assignees', through='api.UserProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_users', through='api.Assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
