# Generated by Django 2.1.7 on 2019-07-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190710_0859'),
        ('api', '0004_auto_20190709_1849'),
    ]

    operations = [
    ]
